# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x89A1c5fB109b4E823A078CE82c9B1cf50704B768"
    chainName: avalanche
    collateralAddressOrDenom: "0x841aef70237a88027ccb2d15c1bbaf88a669674a"
    name: xSpace Token
    standard: EvmHypXERC20
    symbol: xSPACE