# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: avalanche
    standard: EvmHypXERC20
    decimals: 18
    symbol: xSPACE
    name: Space Token
    logoURI: https://spacetoken.tech/assets/images/SPACE.svg
    addressOrDenom: "0x89A1c5fB109b4E823A078CE82c9B1cf50704B768"
    collateralAddressOrDenom: "0x841aef70237a88027ccb2d15c1bbaf88a669674a"        
    connections:
      - token: ethereum|polygon|0x53EEf09D9e5Ec83917788a182837DA48b1C52a15
  - chainName: polygon
    standard: EvmHypXERC20
    decimals: 18
    symbol: xSPACE
    name: Space Token
    logoURI: https://spacetoken.tech/assets/images/SPACE.svg
    addressOrDenom: "0x53EEf09D9e5Ec83917788a182837DA48b1C52a15"
    collateralAddressOrDenom: "0x1D1498166DDCEeE616a6d99868e1E0677300056f"        
    connections:
      - token: ethereum|avalanche|0x89A1c5fB109b4E823A078CE82c9B1cf50704B768
